spring.application.name=spring-ai-rag-orchestrator

# openai api configuration
spring.ai.openai.base-url=${GROQ_BASE_URL}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=${GROQ_MODEL}

# postgresql database configuration
spring.datasource.url=jdbc:postgresql://db.qyyjwqixruivcstalfyv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa / hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
